In [1]:
import pandas as pd
import numpy as np
import openpyxl
import sys
sys.path.append('../')
from src import sp_eda as se

pd.set_option('display.max_columns', None)

### Insertamos los datos del csv

In [2]:

df_acc = pd.read_csv('../data/raw/US_Accidents_March23.csv', low_memory=False)
print("Registros totales de accidentes:", len(df_acc))

df_weather = pd.read_csv('../data/raw/WeatherEvents_Jan2016-Dec2022.csv', low_memory=False)
print("Registros de eventos meteorologicos", len(df_weather))

Registros totales de accidentes: 7728394
Registros de eventos meteorologicos 8627181

Nos quedamos con aquellos del año 2022

In [3]:
y=2022
df_acc["Start_Time"] = pd.to_datetime(df_acc["Start_Time"], errors="coerce")
df_acc_year = df_acc[df_acc["Start_Time"].dt.year.isin([y])]

print(f"Registros de accidentes {y}:", len(df_acc_year))

df_weather["StartTime(UTC)"] = pd.to_datetime(df_weather["StartTime(UTC)"], errors="coerce")
df_weather_year = df_weather[df_weather["StartTime(UTC)"].dt.year.isin([y])]

print(f"Registros de eventos meteorologicos {y}:", len(df_weather_year))

Registros de accidentes 2022: 1268806
Registros de eventos meteorologicos 2022: 1147630

In [4]:
se.eda_prelim(df_weather_year)
df_weather_year.sample(5)

----------
DIMENSIONES
El conjunto de datos presenta 1147630 filas y 14 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
Index: 1147630 entries, 2228 to 8627180
Data columns (total 14 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   EventId            1147630 non-null  str
 1   Type               1147630 non-null  str
 2   Severity           1147630 non-null  str
 3   StartTime(UTC)     1147630 non-null  datetime64[us]
 4   EndTime(UTC)       1147630 non-null  str
 5   Precipitation(in)  1147630 non-null  float64
 6   TimeZone           1147630 non-null  str
 7   AirportCode        1147630 non-null  str
 8   LocationLat        1147630 non-null  float64
 9   LocationLng        1147630 non-null  float64
 10  City               1145281 non-null  str
 11  County             1147630 non-null  str
 12  State              1147630 non-null  str
 13  ZipCode            1137670 non-null  float64
dtypes: datetime64[us](1), float64(4), str(9)
memory usage: 131.3 MB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
EventId              0.000000
Type                 0.000000
Severity             0.000000
StartTime(UTC)       0.000000
EndTime(UTC)         0.000000
Precipitation(in)    0.000000
TimeZone             0.000000
AirportCode          0.000000
LocationLat          0.000000
LocationLng          0.000000
City                 0.204683
County               0.000000
State                0.000000
ZipCode              0.867876
dtype: float64
----------
FRECUENCIA CATEGORÍAS
EventId
W-2229       1
W-2230       1
W-2231       1
W-2232       1
W-2233       1
            ..
W-9091890    1
W-9091891    1
W-9091892    1
W-9091893    1
W-9091894    1
Name: count, Length: 1147630, dtype: int64
-----------
Type
Rain             603152
Fog              291353
Snow             178062
Cold              34414
Precipitation     28349
Storm             12113
Hail                187
Name: count, dtype: int64
-----------
Severity
Light       660343
Severe      268815
Moderate    165045
UNK          28349
Heavy        24891
Other          187
Name: count, dtype: int64
-----------
EndTime(UTC)
2022-12-15 06:15:00    91
2022-12-22 20:55:00    82
2022-12-15 09:15:00    81
2022-12-15 08:15:00    80
2022-11-30 11:15:00    77
                       ..
2022-12-19 08:00:00     1
2022-12-19 09:40:00     1
2022-12-20 16:20:00     1
2022-12-29 16:00:00     1
2022-07-04 23:00:00     1
Name: count, Length: 297716, dtype: int64
-----------
TimeZone
US/Eastern     462844
US/Central     461556
US/Mountain    112582
US/Pacific     110648
Name: count, dtype: int64
-----------
AirportCode
KMLP    2260
K3TH    2260
KDWX    2250
KCEC    1896
KUIL    1816
        ...
KLHM       8
KCQV       6
KREO       5
K4HV       3
KFZG       1
Name: count, Length: 2046, dtype: int64
-----------
City
Jacksonville     4599
Washington       4570
Columbus         4259
Cleveland        4031
Greenville       3998
                 ...
Dryden              8
Colville            6
Jordan Valley       5
Hanksville          3
Fitzgerald          1
Name: count, Length: 1699, dtype: int64
-----------
County
Lincoln       11273
Washington    11010
Montgomery    10379
Jefferson      9802
Marion         8093
              ...
Box Elder        14
Erath            14
Eureka           12
Terrell           8
Ben Hill          1
Name: count, Length: 1094, dtype: int64
-----------
State
MN    68318
TX    67020
MI    60205
FL    47714
NC    47309
CA    42225
WI    42045
GA    38285
VA    36002
IL    35571
WA    33981
IA    32066
PA    30253
OH    30171
NY    28777
OR    26875
ND    25736
SC    25521
AL    25039
WY    24953
LA    24570
CO    23671
OK    22585
AR    21785
IN    21612
MO    17899
MS    17827
KY    17792
MA    17490
NE    16005
WV    14639
MT    14280
ID    13901
KS    13839
ME    13432
SD    12437
TN    11914
NM    11871
MD    10822
NH    10681
NJ     9683
AZ     8605
VT     7764
CT     7585
UT     5941
NV     4617
RI     3851
DE     2466
Name: count, dtype: int64
-----------

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode
6966334,W-7343298,Fog,Severe,2022-08-28 10:55:00,2022-08-28 11:55:00,0.00,US/Central,KCLI,44.6153,-88.7313,Clintonville,Waupaca,WI,54929.0
4093904,W-4316871,Snow,Light,2022-03-12 01:15:00,2022-03-12 03:55:00,0.05,US/Central,KMNE,32.6460,-93.2980,Minden,Webster,LA,71055.0
6098140,W-6428111,Fog,Severe,2022-03-18 09:16:00,2022-03-18 10:36:00,0.00,US/Eastern,KXMR,28.4676,-80.5666,Patrick AFB,Brevard,FL,32925.0
3314971,W-3496081,Rain,Light,2022-07-30 00:25:00,2022-07-30 00:53:00,0.01,US/Central,KARA,30.0292,-91.8845,New Iberia,Iberia,LA,70560.0
3046805,W-3213879,Precipitation,UNK,2022-04-29 18:56:00,2022-04-29 19:56:00,0.36,US/Central,KSZL,38.7303,-93.5479,Washington,Johnson,MO,65305.0

In [5]:
se.eda_prelim(df_acc_year)
df_acc_year.sample(5)

----------
DIMENSIONES
El conjunto de datos presenta 1268806 filas y 46 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
Index: 1268806 entries, 512217 to 5421634
Data columns (total 46 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   ID                     1268806 non-null  str
 1   Source                 1268806 non-null  str
 2   Severity               1268806 non-null  int64
 3   Start_Time             1268806 non-null  datetime64[us]
 4   End_Time               1268806 non-null  str
 5   Start_Lat              1268806 non-null  float64
 6   Start_Lng              1268806 non-null  float64
 7   End_Lat                1032624 non-null  float64
 8   End_Lng                1032624 non-null  float64
 9   Distance(mi)           1268806 non-null  float64
 10  Description            1268806 non-null  str
 11  Street                 1263351 non-null  str
 12  City                   1268763 non-null  str
 13  County                 1268806 non-null  str
 14  State                  1268806 non-null  str
 15  Zipcode                1268612 non-null  str
 16  Country                1268806 non-null  str
 17  Timezone               1267792 non-null  str
 18  Airport_Code           1263939 non-null  str
 19  Weather_Timestamp      1248106 non-null  str
 20  Temperature(F)         1241574 non-null  float64
 21  Wind_Chill(F)          1230424 non-null  float64
 22  Humidity(%)            1239829 non-null  float64
 23  Pressure(in)           1245552 non-null  float64
 24  Visibility(mi)         1239342 non-null  float64
 25  Wind_Direction         1234785 non-null  str
 26  Wind_Speed(mph)        1234791 non-null  float64
 27  Precipitation(in)      1223029 non-null  float64
 28  Weather_Condition      1241709 non-null  str
 29  Amenity                1268806 non-null  bool
 30  Bump                   1268806 non-null  bool
 31  Crossing               1268806 non-null  bool
 32  Give_Way               1268806 non-null  bool
 33  Junction               1268806 non-null  bool
 34  No_Exit                1268806 non-null  bool
 35  Railway                1268806 non-null  bool
 36  Roundabout             1268806 non-null  bool
 37  Station                1268806 non-null  bool
 38  Stop                   1268806 non-null  bool
 39  Traffic_Calming        1268806 non-null  bool
 40  Traffic_Signal         1268806 non-null  bool
 41  Turning_Loop           1268806 non-null  bool
 42  Sunrise_Sunset         1258177 non-null  str
 43  Civil_Twilight         1258177 non-null  str
 44  Nautical_Twilight      1258177 non-null  str
 45  Astronomical_Twilight  1258177 non-null  str
dtypes: bool(13), datetime64[us](1), float64(12), int64(1), str(19)
memory usage: 344.9 MB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
ID                        0.000000
Source                    0.000000
Severity                  0.000000
Start_Time                0.000000
End_Time                  0.000000
Start_Lat                 0.000000
Start_Lng                 0.000000
End_Lat                  18.614508
End_Lng                  18.614508
Distance(mi)              0.000000
Description               0.000000
Street                    0.429932
City                      0.003389
County                    0.000000
State                     0.000000
Zipcode                   0.015290
Country                   0.000000
Timezone                  0.079918
Airport_Code              0.383589
Weather_Timestamp         1.631455
Temperature(F)            2.146270
Wind_Chill(F)             3.025049
Humidity(%)               2.283801
Pressure(in)              1.832747
Visibility(mi)            2.322183
Wind_Direction            2.681340
Wind_Speed(mph)           2.680867
Precipitation(in)         3.607880
Weather_Condition         2.135630
Amenity                   0.000000
Bump                      0.000000
Crossing                  0.000000
Give_Way                  0.000000
Junction                  0.000000
No_Exit                   0.000000
Railway                   0.000000
Roundabout                0.000000
Station                   0.000000
Stop                      0.000000
Traffic_Calming           0.000000
Traffic_Signal            0.000000
Turning_Loop              0.000000
Sunrise_Sunset            0.837717
Civil_Twilight            0.837717
Nautical_Twilight         0.837717
Astronomical_Twilight     0.837717
dtype: float64
----------
FRECUENCIA CATEGORÍAS
ID
A-512230     1
A-512231     1
A-512232     1
A-512233     1
A-512234     1
            ..
A-5462838    1
A-5462839    1
A-5462840    1
A-5462841    1
A-5462842    1
Name: count, Length: 1268806, dtype: int64
-----------
Source
Source1    1032624
Source2     219411
Source3      16771
Name: count, dtype: int64
-----------
End_Time
2022-08-18 13:45:00    31
2022-12-22 20:45:00    28
2022-01-05 13:59:00    27
2022-08-04 14:28:11    27
2022-07-29 08:51:46    26
                       ..
2022-09-16 17:15:58     1
2022-01-17 15:28:05     1
2022-12-01 20:39:50     1
2022-05-20 17:20:36     1
2022-02-01 16:43:36     1
Name: count, Length: 1022891, dtype: int64
-----------
Description
Accident                                                                                                                          2800
A crash has occurred causing no to minimum delays. Use caution.                                                                   2132
An unconfirmed report of a crash has been received. Use caution.                                                                  1301
A crash has occurred with minimal delay to traffic. Prepare to slow or move over for worker safety.                                934
A crash has occurred use caution.                                                                                                  687
                                                                                                                                  ...
Slow traffic on I-70 W - CO-9 S - US-6 W from US-6/Exit 216 (I-70) to CR-16/Shrine Pass Rd/Exit 190 (I-70) due to accident.          1
Accident from W 400 S to I-15 N.                                                                                                     1
Stationary traffic on FL-869 N from FL-834/Sample Rd/Exit 8 (FL-869) to US-441/Exit 15 (FL-869) due to accident.                     1
Slow traffic on Wilbur Cross Pkwy N - CT-15 N from CT-150/Hall Ave/Exit 65 (CT-15) to I-691/Exit 68 W (CT-15) due to accident.       1
Stationary traffic on US-29 N - NC-49 from Honduras Dr to W Craighead Rd due to accident.                                            1
Name: count, Length: 781102, dtype: int64
-----------
Street
I-95 S               11996
I-95 N               11051
I-95                  9306
I-5 N                 8000
I-10 E                7548
                     ...
 Rebecca Rd              1
E Tonopah Dr             1
 Statesville Blvd        1
Line Creek Trl           1
 NW 114th Way            1
Name: count, Length: 143467, dtype: int64
-----------
City
Miami          44223
Orlando        25309
Los Angeles    22220
Houston        19407
Dallas         18256
               ...
Whiting            1
Westerlo           1
Boyd               1
Kresgeville        1
Parkston           1
Name: count, Length: 10171, dtype: int64
-----------
County
Los Angeles    73976
Miami-Dade     61696
Orange         47292
Dallas         22695
Montgomery     21511
               ...
Atchison           1
Doniphan           1
Bosque             1
St. Bernard        1
Tom Green          1
Name: count, Length: 1634, dtype: int64
-----------
State
CA    266275
FL    186101
TX     71725
VA     69801
NY     66498
SC     63161
PA     57583
NC     53044
NJ     29943
AZ     28176
TN     28039
MN     26514
MD     26034
GA     24509
LA     24488
MI     21005
OR     20579
OH     20338
IL     19463
AL     16719
CO     15222
MO     14291
CT     14288
UT     12590
WA     11567
IN     10641
MT      9631
OK      7273
AR      6513
MA      6005
WI      5661
DC      4893
KS      4611
WV      3610
IA      3521
NV      3131
MS      2569
KY      2426
DE      2299
ID      1553
WY      1389
RI      1374
NM      1162
NE      1132
ND       821
NH       474
ME       105
VT        37
SD        22
Name: count, dtype: int64
-----------
Zipcode
33186         1962
32819         1875
91761         1511
32837         1397
92407         1375
              ...
33178-1177       1
23060-6215       1
75702-8413       1
94303-4622       1
23669-2307       1
Name: count, Length: 244692, dtype: int64
-----------
Country
US    1268806
Name: count, dtype: int64
-----------
Timezone
US/Eastern     662326
US/Pacific     305728
US/Central     228388
US/Mountain     71350
NaN              1014
Name: count, dtype: int64
-----------
Airport_Code
KMIA    19298
KOPF    18090
KCQT    16978
KORL    16221
KRDU    15475
        ...
KPDC        1
KSMN        1
KSZT        1
KSJT        1
KMHE        1
Name: count, Length: 1903, dtype: int64
-----------
Weather_Timestamp
NaN                    20700
2022-03-13 01:53:00      951
2022-05-13 16:53:00      384
2022-03-13 01:55:00      372
2022-05-17 15:53:00      368
                       ...
2022-12-27 22:22:00        1
2022-10-03 18:23:00        1
2022-04-12 06:19:00        1
2022-05-24 23:54:00        1
2022-12-01 19:34:00        1
Name: count, Length: 133984, dtype: int64
-----------
Wind_Direction
CALM    202181
S       100138
W        90751
N        69785
E        65360
SSW      63899
VAR      63018
WNW      62798
NW       60851
SW       60305
WSW      59019
SSE      56564
NNW      54877
SE       49964
ESE      47697
ENE      43182
NE       42973
NNE      41423
NaN      34021
Name: count, dtype: int64
-----------
Weather_Condition
Fair                           623334
Mostly Cloudy                  164747
Cloudy                         162841
Partly Cloudy                  114422
Light Rain                      48874
                                ...
Squalls                             2
Heavy Freezing Rain / Windy         1
Heavy Freezing Drizzle              1
Sand / Dust Whirls Nearby           1
Thunder and Hail / Windy            1
Name: count, Length: 91, dtype: int64
-----------
Sunrise_Sunset
Day      906365
Night    351812
NaN       10629
Name: count, dtype: int64
-----------
Civil_Twilight
Day      960762
Night    297415
NaN       10629
Name: count, dtype: int64
-----------
Nautical_Twilight
Day      1019479
Night     238698
NaN        10629
Name: count, dtype: int64
-----------
Astronomical_Twilight
Day      1065999
Night     192178
NaN        10629
Name: count, dtype: int64
-----------

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Street,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
4011891,A-4042003,Source1,2,2022-07-29 16:19:00,2022-07-29 19:05:30,37.700672,-121.798202,37.740264,-121.585871,11.923,Stationary traffic on I-580 E from Airway Blvd...,I-580 E,Livermore,Alameda,CA,94551,US,US/Pacific,KLVK,2022-07-29 15:53:00,80.0,80.0,47.0,29.40,10.0,WNW,16.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
5033158,A-5071297,Source1,2,2022-08-21 22:51:00,2022-08-22 00:07:19,42.745804,-83.407308,42.743301,-83.392581,0.767,Incident on I-75 SB near M-15 Drive with caution.,Chrysler Expy S,Clarkston,Oakland,MI,48348,US,US/Eastern,KPTK,2022-08-21 22:53:00,68.0,68.0,87.0,28.90,10.0,N,5.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
4497801,A-4531875,Source1,2,2022-09-15 20:39:35,2022-09-15 21:57:36,38.866662,-78.530067,38.869270,-78.528646,0.196,Incident on I-81 NB near MM 283 Drive with cau...,I-81 N,Woodstock,Shenandoah,VA,22664,US,US/Eastern,KLUA,2022-09-15 20:35:00,66.0,66.0,83.0,29.23,10.0,CALM,0.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Day
5061475,A-5099840,Source1,2,2022-11-04 18:48:00,2022-11-04 20:07:58,34.106986,-117.923839,34.106994,-117.923254,0.033,Incident on W ARROW HWY near HOUSE 1151 Drive ...,W Arrow Hwy,Azusa,Los Angeles,CA,91702-5141,US,US/Pacific,KEMT,2022-11-04 18:53:00,63.0,63.0,29.0,30.09,10.0,W,6.0,0.0,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Day,Day
3814737,A-3843328,Source1,2,2022-08-24 07:55:42,2022-08-24 09:13:42,37.442616,-77.687673,37.442498,-77.688816,0.063,Incident on GENITO RD near GENITO RD Drive wit...,Genito Rd,Midlothian,Chesterfield,VA,23112-5100,US,US/Eastern,KFCI,2022-08-24 07:56:00,68.0,68.0,100.0,29.77,10.0,CALM,0.0,0.0,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

###  Combinación del dataframe Accidentes con dataframe de Eventos meteorológicos.
Se ha decidido agrupar los accidentes y eventos por estado y día del suceso.
Además se va a añadir los subtotales del grado de severidad de accidente. Lo mismo se va a hacer con el dataframe de eventos meteorologicos, manteniendo subtotales de severidad meteorologica y tipo de evento evento meteorologico.

Se crea la columna date de ambos dataframe

In [6]:
df_acc_year["Date"] = df_acc_year["Start_Time"].dt.date
df_weather_year["Date"] = df_weather_year["StartTime(UTC)"].dt.date

Contamos los eventos meteorologicos por aeropuerto estado y día.

In [54]:
weather_tot_events = (
    df_weather_year
    .groupby(["State", "Date"])
    .size()
    .reset_index(name="weather_events")
)

Añadimos cuenta con el tipo de evento meteorologico

In [55]:
weather_by_type = (
    df_weather_year
    .groupby(["State","Date", "Type"])
    .size()
    .unstack(fill_value=0)
    .add_prefix("typ_")
    .reset_index()
)

Añadimos cuenta con la severidad

In [56]:
weather_by_severity = (
    df_weather_year
    .groupby(["State", "Date", "Type"])
    .size()
    .unstack(fill_value=0)
    .add_prefix("wea_sev_")
    .reset_index()
)

Lo unificamos todo en un data frame

In [57]:
weather_agg = (
    weather_tot_events
    .merge(weather_by_type, on=["State", "Date"], how="left")
    .merge(weather_by_severity, on=["State", "Date"], how="left")
)

In [58]:
se.eda_prelim(weather_agg)
weather_agg.sample(5)

----------
DIMENSIONES
El conjunto de datos presenta 16714 filas y 17 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
RangeIndex: 16714 entries, 0 to 16713
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State                  16714 non-null  str
 1   Date                   16714 non-null  object
 2   weather_events         16714 non-null  int64
 3   typ_Cold               16714 non-null  int64
 4   typ_Fog                16714 non-null  int64
 5   typ_Hail               16714 non-null  int64
 6   typ_Precipitation      16714 non-null  int64
 7   typ_Rain               16714 non-null  int64
 8   typ_Snow               16714 non-null  int64
 9   typ_Storm              16714 non-null  int64
 10  wea_sev_Cold           16714 non-null  int64
 11  wea_sev_Fog            16714 non-null  int64
 12  wea_sev_Hail           16714 non-null  int64
 13  wea_sev_Precipitation  16714 non-null  int64
 14  wea_sev_Rain           16714 non-null  int64
 15  wea_sev_Snow           16714 non-null  int64
 16  wea_sev_Storm          16714 non-null  int64
dtypes: int64(15), object(1), str(1)
memory usage: 2.2+ MB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
State                    0.0
Date                     0.0
weather_events           0.0
typ_Cold                 0.0
typ_Fog                  0.0
typ_Hail                 0.0
typ_Precipitation        0.0
typ_Rain                 0.0
typ_Snow                 0.0
typ_Storm                0.0
wea_sev_Cold             0.0
wea_sev_Fog              0.0
wea_sev_Hail             0.0
wea_sev_Precipitation    0.0
wea_sev_Rain             0.0
wea_sev_Snow             0.0
wea_sev_Storm            0.0
dtype: float64
----------
FRECUENCIA CATEGORÍAS
State
CA    365
FL    365
MI    365
OR    365
TX    365
WA    365
WI    365
GA    364
MN    364
NC    364
ND    364
LA    362
MS    362
NY    362
OH    362
PA    362
CT    361
AL    360
IA    360
ID    360
IL    360
VA    360
WY    359
SC    358
CO    357
MT    357
OK    357
AR    356
IN    354
MO    352
NH    351
TN    351
WV    351
ME    349
MA    347
MD    346
NM    346
NE    344
KY    342
KS    341
VT    339
SD    338
AZ    335
UT    314
NJ    310
NV    287
RI    254
DE    237
Name: count, dtype: int64
-----------
Date
2022-01-01    48
2022-01-20    48
2022-02-02    48
2022-02-22    48
2022-02-23    48
              ..
2022-04-25    40
2022-11-23    40
2022-02-27    38
2022-02-20    37
2022-03-13    31
Name: count, Length: 365, dtype: int64
-----------

,State,Date,weather_events,typ_Cold,typ_Fog,typ_Hail,typ_Precipitation,typ_Rain,typ_Snow,typ_Storm,wea_sev_Cold,wea_sev_Fog,wea_sev_Hail,wea_sev_Precipitation,wea_sev_Rain,wea_sev_Snow,wea_sev_Storm
1647,CO,2022-08-25,41,6,0,0,0,35,0,0,6,0,0,0,35,0,0
14553,UT,2022-12-10,3,0,3,0,0,0,0,0,0,3,0,0,0,0,0
4656,KS,2022-05-17,32,0,1,0,1,27,0,3,0,1,0,1,27,0,3
2110,CT,2022-12-08,5,3,2,0,0,0,0,0,3,2,0,0,0,0,0
378,AR,2022-01-19,74,0,11,0,0,49,14,0,0,11,0,0,49,14,0

Vamos a agrupar el numero total de accidentes por día y estado añadiendo el subtotal segun la severidad del accidente.

In [59]:
acc_tot = (
    df_acc_year
    .groupby(["State", "Date"])
    .size()
    .reset_index(name="acc_events"))

In [60]:
acc_by_severity = (
    df_acc_year
    .groupby(["State", "Date", "Severity"])
    .size()
    .unstack(fill_value=0)
    .add_prefix("acc_sev_")
    .reset_index())

Unimos ambos

In [61]:
acc_agg = (
    acc_tot
    .merge(acc_by_severity, on=["State", "Date"], how="left")
)

In [62]:
se.eda_prelim(acc_agg)
acc_agg.sample(5)

----------
DIMENSIONES
El conjunto de datos presenta 14431 filas y 7 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
RangeIndex: 14431 entries, 0 to 14430
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State       14431 non-null  str
 1   Date        14431 non-null  object
 2   acc_events  14431 non-null  int64
 3   acc_sev_1   14431 non-null  int64
 4   acc_sev_2   14431 non-null  int64
 5   acc_sev_3   14431 non-null  int64
 6   acc_sev_4   14431 non-null  int64
dtypes: int64(5), object(1), str(1)
memory usage: 789.3+ KB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
State         0.0
Date          0.0
acc_events    0.0
acc_sev_1     0.0
acc_sev_2     0.0
acc_sev_3     0.0
acc_sev_4     0.0
dtype: float64
----------
FRECUENCIA CATEGORÍAS
State
SC    341
LA    336
NY    336
OR    335
WA    335
AZ    334
CA    334
MI    334
MN    334
NC    334
FL    333
GA    333
NJ    333
TX    333
AL    332
CO    332
CT    332
MO    332
MT    332
PA    332
TN    332
UT    332
VA    332
IL    331
IN    331
MD    331
OK    331
AR    330
DC    329
WV    326
KS    324
NV    324
IA    322
DE    319
WI    319
OH    305
MS    299
RI    283
KY    277
MA    274
ID    250
NE    247
NM    245
ND    203
WY    190
NH    160
ME     70
VT     32
SD      6
Name: count, dtype: int64
-----------
Date
2022-02-03    48
2022-01-12    47
2022-01-14    47
2022-01-21    47
2022-01-24    47
              ..
2022-05-08     1
2022-05-09     1
2022-10-21     1
2022-10-29     1
2022-03-28     1
Name: count, Length: 348, dtype: int64
-----------

,State,Date,acc_events,acc_sev_1,acc_sev_2,acc_sev_3,acc_sev_4
8734,NJ,2022-01-07,3,0,2,0,1
585,AR,2022-09-27,21,0,16,0,5
9301,NM,2022-12-23,1,0,1,0,0
12334,TX,2022-04-21,228,0,197,30,1
9792,NY,2022-06-22,224,1,211,10,2

Creamos nuestro dataframe final con el agregado de accidentes con eventos meteorologicos

In [63]:
df_final = acc_agg.merge(
    weather_agg,
    on=["State", "Date"],
    how="left"
)

Se van a añadir los nombres de los estados de estados unidos para tener más claro los datos

In [64]:
df_states = pd.read_csv('../data/raw/United States - Region Codes.csv', low_memory=False)
df_states.sample(5)

          Region Region code                   Country
46      Virginia       us-va  United States of America
37        Oregon       us-or  United States of America
14       Indiana       us-in  United States of America
35          Ohio       us-oh  United States of America
39  Rhode Island       us-ri  United States of America

VAmos a cambiar los nombres de las columnas para hacer el merge y a estandarizar los registros de los codigos de estado con el fin de hacerlos conicidir con el df_final poniendolos en mayúsculas y eliminando el "US-"

In [72]:
df_states= df_states.rename(columns={"Region code": "State","Region":"Name"})
df_states["State"] = df_states["State"].str.upper()
df_states["State"] = df_states["State"].str.replace("US-", "", regex=False)
df_states.sample(5)

          Name State                   Country
47  Washington    WA  United States of America
43       Texas    TX  United States of America
31  New Mexico    NM  United States of America
11      Hawaii    HI  United States of America
10     Georgia    GA  United States of America

Introducimos en nuestro df_final el nombre del estado para una mayor comprension de los datos

In [70]:
df_final = df_final.merge(
    df_states[["State", "Name"]],
    on="State",
    how="left")

In [71]:
se.eda_prelim(df_final)

----------
DIMENSIONES
El conjunto de datos presenta 14431 filas y 23 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
RangeIndex: 14431 entries, 0 to 14430
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State                  14431 non-null  str
 1   Date                   14431 non-null  object
 2   acc_events             14431 non-null  int64
 3   acc_sev_1              14431 non-null  int64
 4   acc_sev_2              14431 non-null  int64
 5   acc_sev_3              14431 non-null  int64
 6   acc_sev_4              14431 non-null  int64
 7   weather_events         13492 non-null  float64
 8   typ_Cold               13492 non-null  float64
 9   typ_Fog                13492 non-null  float64
 10  typ_Hail               13492 non-null  float64
 11  typ_Precipitation      13492 non-null  float64
 12  typ_Rain               13492 non-null  float64
 13  typ_Snow               13492 non-null  float64
 14  typ_Storm              13492 non-null  float64
 15  wea_sev_Cold           13492 non-null  float64
 16  wea_sev_Fog            13492 non-null  float64
 17  wea_sev_Hail           13492 non-null  float64
 18  wea_sev_Precipitation  13492 non-null  float64
 19  wea_sev_Rain           13492 non-null  float64
 20  wea_sev_Snow           13492 non-null  float64
 21  wea_sev_Storm          13492 non-null  float64
 22  Name                   14431 non-null  str
dtypes: float64(15), int64(5), object(1), str(2)
memory usage: 2.5+ MB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
State                    0.000000
Date                     0.000000
acc_events               0.000000
acc_sev_1                0.000000
acc_sev_2                0.000000
acc_sev_3                0.000000
acc_sev_4                0.000000
weather_events           6.506826
typ_Cold                 6.506826
typ_Fog                  6.506826
typ_Hail                 6.506826
typ_Precipitation        6.506826
typ_Rain                 6.506826
typ_Snow                 6.506826
typ_Storm                6.506826
wea_sev_Cold             6.506826
wea_sev_Fog              6.506826
wea_sev_Hail             6.506826
wea_sev_Precipitation    6.506826
wea_sev_Rain             6.506826
wea_sev_Snow             6.506826
wea_sev_Storm            6.506826
Name                     0.000000
dtype: float64
----------
FRECUENCIA CATEGORÍAS
State
SC    341
LA    336
NY    336
OR    335
WA    335
AZ    334
CA    334
MI    334
MN    334
NC    334
FL    333
GA    333
NJ    333
TX    333
AL    332
CO    332
CT    332
MO    332
MT    332
PA    332
TN    332
UT    332
VA    332
IL    331
IN    331
MD    331
OK    331
AR    330
DC    329
WV    326
KS    324
NV    324
IA    322
DE    319
WI    319
OH    305
MS    299
RI    283
KY    277
MA    274
ID    250
NE    247
NM    245
ND    203
WY    190
NH    160
ME     70
VT     32
SD      6
Name: count, dtype: int64
-----------
Date
2022-02-03    48
2022-01-12    47
2022-01-14    47
2022-01-21    47
2022-01-24    47
              ..
2022-05-08     1
2022-05-09     1
2022-10-21     1
2022-10-29     1
2022-03-28     1
Name: count, Length: 348, dtype: int64
-----------
Name
South Carolina          341
Louisiana               336
New York                336
Oregon                  335
Washington              335
Arizona                 334
California              334
Michigan                334
Minnesota               334
North Carolina          334
Florida                 333
Georgia                 333
New Jersey              333
Texas                   333
Alabama                 332
Colorado                332
Connecticut             332
Missouri                332
Montana                 332
Pennsylvania            332
Tennessee               332
Utah                    332
Virginia                332
Illinois                331
Indiana                 331
Maryland                331
Oklahoma                331
Arkansas                330
District of Columbia    329
West Virginia           326
Kansas                  324
Nevada                  324
Iowa                    322
Delaware                319
Wisconsin               319
Ohio                    305
Mississippi             299
Rhode Island            283
Kentucky                277
Massachusetts           274
Idaho                   250
Nebraska                247
New Mexico              245
North Dakota            203
Wyoming                 190
New Hampshire           160
Maine                    70
Vermont                  32
South Dakota              6
Name: count, dtype: int64
-----------

Guardamos nuestro nuevo archivo con ambos archivos juntos y pasamos a la limpieza

In [73]:
df_final.to_csv('../data/Acc_met.csv', index=False)