In [9]:
import pandas as pd
import numpy as np
from src import sp_eda as se
import openpyxl
import locale
import sys
sys.path.append('../')
pd.set_option('display.max_columns', None)

Insertamos el dataframe y lo copiamos

In [6]:
df_raw=pd.read_csv('../data/Acc_met.csv')

df=df_raw.copy()
df.sample(5)

,State,Date,acc_events,acc_sev_1,acc_sev_2,acc_sev_3,acc_sev_4,weather_events,typ_Cold,typ_Fog,typ_Hail,typ_Precipitation,typ_Rain,typ_Snow,typ_Storm,wea_sev_Heavy,wea_sev_Light,wea_sev_Moderate,wea_sev_Other,wea_sev_Severe,wea_sev_UNK,Name
11420,RI,2022-06-22,6,2,1,3,0,11.0,0.0,2.0,0.0,0.0,9.0,0.0,0.0,0.0,9.0,0.0,0.0,2.0,0.0,Rhode Island
6841,MO,2022-01-22,9,0,9,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Missouri
11489,RI,2022-09-05,8,1,5,2,0,27.0,0.0,0.0,0.0,1.0,26.0,0.0,0.0,6.0,13.0,7.0,0.0,0.0,1.0,Rhode Island
8016,NC,2022-09-03,106,0,93,6,7,61.0,2.0,28.0,0.0,0.0,31.0,0.0,0.0,0.0,30.0,1.0,0.0,30.0,0.0,North Carolina
6783,MN,2022-11-18,72,0,72,0,0,465.0,10.0,35.0,0.0,0.0,2.0,418.0,0.0,1.0,419.0,28.0,0.0,17.0,0.0,Minnesota

Movemos la columna de posición y cambiamos de nombre la columna con el codigo de estado.

In [7]:
col = "Name"
cols = list(df.columns)
cols.insert(1, cols.pop(cols.index(col)))
df= df[cols]
df = df.rename(columns={
    "State": "State_code",
    "Name": "State"
})



df.sample(5)

,State_code,State,Date,acc_events,acc_sev_1,acc_sev_2,acc_sev_3,acc_sev_4,weather_events,typ_Cold,typ_Fog,typ_Hail,typ_Precipitation,typ_Rain,typ_Snow,typ_Storm,wea_sev_Heavy,wea_sev_Light,wea_sev_Moderate,wea_sev_Other,wea_sev_Severe,wea_sev_UNK
11008,PA,Pennsylvania,2022-03-14,237,0,204,19,14,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
11407,RI,Rhode Island,2022-06-08,8,1,3,4,0,43.0,0.0,10.0,0.0,1.0,32.0,0.0,0.0,5.0,19.0,12.0,0.0,6.0,1.0
13143,VA,Virginia,2022-09-19,190,0,172,0,18,75.0,18.0,53.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,13.0,0.0,58.0,0.0
3607,IA,Iowa,2022-12-09,7,0,7,0,0,547.0,4.0,230.0,0.0,0.0,158.0,155.0,0.0,23.0,232.0,61.0,0.0,231.0,0.0
6819,MN,Minnesota,2022-12-29,75,0,75,0,0,184.0,3.0,129.0,0.0,0.0,16.0,36.0,0.0,0.0,52.0,13.0,0.0,119.0,0.0

In [10]:
se.eda_prelim(df)

----------
DIMENSIONES
El conjunto de datos presenta 14431 filas y 22 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
RangeIndex: 14431 entries, 0 to 14430
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State_code         14431 non-null  str
 1   State              14431 non-null  str
 2   Date               14431 non-null  str
 3   acc_events         14431 non-null  int64
 4   acc_sev_1          14431 non-null  int64
 5   acc_sev_2          14431 non-null  int64
 6   acc_sev_3          14431 non-null  int64
 7   acc_sev_4          14431 non-null  int64
 8   weather_events     13492 non-null  float64
 9   typ_Cold           13492 non-null  float64
 10  typ_Fog            13492 non-null  float64
 11  typ_Hail           13492 non-null  float64
 12  typ_Precipitation  13492 non-null  float64
 13  typ_Rain           13492 non-null  float64
 14  typ_Snow           13492 non-null  float64
 15  typ_Storm          13492 non-null  float64
 16  wea_sev_Heavy      13492 non-null  float64
 17  wea_sev_Light      13492 non-null  float64
 18  wea_sev_Moderate   13492 non-null  float64
 19  wea_sev_Other      13492 non-null  float64
 20  wea_sev_Severe     13492 non-null  float64
 21  wea_sev_UNK        13492 non-null  float64
dtypes: float64(14), int64(5), str(3)
memory usage: 2.4 MB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
State_code           0.000000
State                0.000000
Date                 0.000000
acc_events           0.000000
acc_sev_1            0.000000
acc_sev_2            0.000000
acc_sev_3            0.000000
acc_sev_4            0.000000
weather_events       6.506826
typ_Cold             6.506826
typ_Fog              6.506826
typ_Hail             6.506826
typ_Precipitation    6.506826
typ_Rain             6.506826
typ_Snow             6.506826
typ_Storm            6.506826
wea_sev_Heavy        6.506826
wea_sev_Light        6.506826
wea_sev_Moderate     6.506826
wea_sev_Other        6.506826
wea_sev_Severe       6.506826
wea_sev_UNK          6.506826
dtype: float64
----------
FRECUENCIA CATEGORÍAS
State_code
SC    341
LA    336
NY    336
OR    335
WA    335
AZ    334
CA    334
MI    334
MN    334
NC    334
FL    333
GA    333
NJ    333
TX    333
AL    332
CO    332
CT    332
MO    332
MT    332
PA    332
TN    332
UT    332
VA    332
IL    331
IN    331
MD    331
OK    331
AR    330
DC    329
WV    326
KS    324
NV    324
IA    322
DE    319
WI    319
OH    305
MS    299
RI    283
KY    277
MA    274
ID    250
NE    247
NM    245
ND    203
WY    190
NH    160
ME     70
VT     32
SD      6
Name: count, dtype: int64
-----------
State
South Carolina          341
Louisiana               336
New York                336
Oregon                  335
Washington              335
Arizona                 334
California              334
Michigan                334
Minnesota               334
North Carolina          334
Florida                 333
Georgia                 333
New Jersey              333
Texas                   333
Alabama                 332
Colorado                332
Connecticut             332
Missouri                332
Montana                 332
Pennsylvania            332
Tennessee               332
Utah                    332
Virginia                332
Illinois                331
Indiana                 331
Maryland                331
Oklahoma                331
Arkansas                330
District of Columbia    329
West Virginia           326
Kansas                  324
Nevada                  324
Iowa                    322
Delaware                319
Wisconsin               319
Ohio                    305
Mississippi             299
Rhode Island            283
Kentucky                277
Massachusetts           274
Idaho                   250
Nebraska                247
New Mexico              245
North Dakota            203
Wyoming                 190
New Hampshire           160
Maine                    70
Vermont                  32
South Dakota              6
Name: count, dtype: int64
-----------
Date
2022-02-03    48
2022-01-12    47
2022-01-14    47
2022-01-21    47
2022-01-24    47
              ..
2022-05-08     1
2022-05-09     1
2022-10-21     1
2022-10-29     1
2022-03-28     1
Name: count, Length: 348, dtype: int64
-----------

Se van a unificar el tipo de datos de las columnas y vamos a usar tipo int, ya que para contar eventos nos es más que suficiente y es más eficiente.
En las filas de severidad de eventos meteorologicos, vamos a sustituir NsN por 0.

In [12]:

cols = df.columns[7:21]

df[cols] = df[cols].fillna(0).astype("int64")

Por otro lado, en la clasificación de eventos meteorologicos, existen dos tipos que vamos a unificar, ya que la información que aportan por separado no aporta más que toda ella junta (other y unknown).

In [14]:
df["wea_sev_UNKNOWN"] = df["wea_sev_UNK"] + df["wea_sev_Other"]

df = df.drop(columns=["wea_sev_UNK", "wea_sev_Other"])

Ponemos los nombres de las columnas todas en mayúsculas por estandarizar

In [16]:
df.columns = df.columns.str.upper()

In [17]:
se.eda_prelim(df)

----------
DIMENSIONES
El conjunto de datos presenta 14431 filas y 21 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
RangeIndex: 14431 entries, 0 to 14430
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   STATE_CODE         14431 non-null  str
 1   STATE              14431 non-null  str
 2   DATE               14431 non-null  str
 3   ACC_EVENTS         14431 non-null  int64
 4   ACC_SEV_1          14431 non-null  int64
 5   ACC_SEV_2          14431 non-null  int64
 6   ACC_SEV_3          14431 non-null  int64
 7   ACC_SEV_4          14431 non-null  int64
 8   WEATHER_EVENTS     14431 non-null  int64
 9   TYP_COLD           14431 non-null  int64
 10  TYP_FOG            14431 non-null  int64
 11  TYP_HAIL           14431 non-null  int64
 12  TYP_PRECIPITATION  14431 non-null  int64
 13  TYP_RAIN           14431 non-null  int64
 14  TYP_SNOW           14431 non-null  int64
 15  TYP_STORM          14431 non-null  int64
 16  WEA_SEV_HEAVY      14431 non-null  int64
 17  WEA_SEV_LIGHT      14431 non-null  int64
 18  WEA_SEV_MODERATE   14431 non-null  int64
 19  WEA_SEV_SEVERE     14431 non-null  int64
 20  WEA_SEV_UNKNOWN    13492 non-null  float64
dtypes: float64(1), int64(17), str(3)
memory usage: 2.3 MB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
STATE_CODE           0.000000
STATE                0.000000
DATE                 0.000000
ACC_EVENTS           0.000000
ACC_SEV_1            0.000000
ACC_SEV_2            0.000000
ACC_SEV_3            0.000000
ACC_SEV_4            0.000000
WEATHER_EVENTS       0.000000
TYP_COLD             0.000000
TYP_FOG              0.000000
TYP_HAIL             0.000000
TYP_PRECIPITATION    0.000000
TYP_RAIN             0.000000
TYP_SNOW             0.000000
TYP_STORM            0.000000
WEA_SEV_HEAVY        0.000000
WEA_SEV_LIGHT        0.000000
WEA_SEV_MODERATE     0.000000
WEA_SEV_SEVERE       0.000000
WEA_SEV_UNKNOWN      6.506826
dtype: float64
----------
FRECUENCIA CATEGORÍAS
STATE_CODE
SC    341
LA    336
NY    336
OR    335
WA    335
AZ    334
CA    334
MI    334
MN    334
NC    334
FL    333
GA    333
NJ    333
TX    333
AL    332
CO    332
CT    332
MO    332
MT    332
PA    332
TN    332
UT    332
VA    332
IL    331
IN    331
MD    331
OK    331
AR    330
DC    329
WV    326
KS    324
NV    324
IA    322
DE    319
WI    319
OH    305
MS    299
RI    283
KY    277
MA    274
ID    250
NE    247
NM    245
ND    203
WY    190
NH    160
ME     70
VT     32
SD      6
Name: count, dtype: int64
-----------
STATE
South Carolina          341
Louisiana               336
New York                336
Oregon                  335
Washington              335
Arizona                 334
California              334
Michigan                334
Minnesota               334
North Carolina          334
Florida                 333
Georgia                 333
New Jersey              333
Texas                   333
Alabama                 332
Colorado                332
Connecticut             332
Missouri                332
Montana                 332
Pennsylvania            332
Tennessee               332
Utah                    332
Virginia                332
Illinois                331
Indiana                 331
Maryland                331
Oklahoma                331
Arkansas                330
District of Columbia    329
West Virginia           326
Kansas                  324
Nevada                  324
Iowa                    322
Delaware                319
Wisconsin               319
Ohio                    305
Mississippi             299
Rhode Island            283
Kentucky                277
Massachusetts           274
Idaho                   250
Nebraska                247
New Mexico              245
North Dakota            203
Wyoming                 190
New Hampshire           160
Maine                    70
Vermont                  32
South Dakota              6
Name: count, dtype: int64
-----------
DATE
2022-02-03    48
2022-01-12    47
2022-01-14    47
2022-01-21    47
2022-01-24    47
              ..
2022-05-08     1
2022-05-09     1
2022-10-21     1
2022-10-29     1
2022-03-28     1
Name: count, Length: 348, dtype: int64
-----------